dist: trusty
language: java
before_install:
  - rm ~/.m2/settings.xml
  - git clone https://github.com/cmebarrow/nukleus-kafka.spec
  - cd nukleus-kafka.spec
  - git checkout fix_npes_2
  - mvn clean install -DskipTests
  - cd ..
jdk:
  - oraclejdk8
install: mvn -v
script: mvn -B -nsu verify
cache:
  directories:
    - $HOME/.m2
branches:
  except:
  - /^release\/.*$/
